import {test,expect,type Locator} from '@playwright/test';

test('FC landscape layout, simultaneous keys, rotation release and top-right app cycle',async({browser})=>{
 const ctx=await browser.newContext({hasTouch:true});
 const tablet=await ctx.newPage(),phone=await ctx.newPage();
 const errors:string[]=[];phone.on('pageerror',e=>errors.push(e.message));
 await phone.setViewportSize({width:844,height:390});
 await tablet.goto('/?bridge=5191');
 await tablet.getByRole('button',{name:'连接设置',exact:true}).click();
 const pin=await tablet.locator('.pair-code').innerText();
 await tablet.locator('.scrim').click({position:{x:5,y:5}});
 await phone.goto('/?role=phone&bridge=5191');
 await phone.getByLabel('平板地址').fill('localhost');
 await phone.getByLabel('配对码',{exact:true}).fill(pin);
 await phone.getByRole('button',{name:'连接',exact:true}).click();
 await expect(phone.getByText('已连接工作台')).toBeVisible();
 await tablet.getByRole('button',{name:'Super Mario',exact:true}).click();
 await expect(tablet.locator('.game')).toHaveAttribute('data-ready','true',{timeout:15000});
 await expect(phone.locator('.fc-stage')).toHaveAttribute('data-layout','landscape');
 await phone.evaluate(()=>document.fonts.ready);
 await expect(phone.locator('.fc-home-line')).toHaveCount(0);
 const stage=(await phone.locator('.fc-stage').boundingBox())!;expect(stage.x+stage.width/2).toBeCloseTo(422);expect(stage.y+stage.height/2).toBeCloseTo(195);
 const game=(await tablet.locator('.game').boundingBox())!;expect(game).toMatchObject({x:0,y:0,width:1400,height:920});
 await expect(tablet.locator('.systembar')).toHaveCount(0);await expect(tablet.locator('.windowbar')).toBeHidden();
 await expect(tablet.getByRole('button',{name:'返回',exact:true})).toBeVisible();

 const switcher=phone.getByRole('button',{name:'切换应用',exact:true});
 const box=(await switcher.boundingBox())!;
 const scale=1;expect(box.x).toBeCloseTo(stage.x+772*scale,0);expect(box.y).toBeCloseTo(stage.y+18*scale,0);
 expect(box.width).toBeCloseTo(48*scale,0);expect(box.height).toBeCloseTo(48*scale,0);
 expect(await phone.locator('.fc-stage img').evaluateAll(images=>images.every(n=>(n as HTMLImageElement).complete&&(n as HTMLImageElement).naturalWidth>0))).toBe(true);
 await phone.screenshot({path:'artifacts/visual-qa/fc-figma-landscape.png'});
 const frame=tablet.frames().find(f=>f.url().includes('mario-classic'))!;
 await frame.evaluate(()=>window.addEventListener('message',e=>{if(e.data?.kind==='mobile-control')(window as any).__receivedKeys=e.data.keys;}));
 const keys=()=>frame.evaluate(()=>(window as any).__marioState?.keys||[]);
 const cdp=await ctx.newCDPSession(phone);
 const point=async(locator:Locator,id:number)=>{const b=(await locator.boundingBox())!;return {x:b.x+b.width/2,y:b.y+b.height/2,id};};
 const right=await point(phone.getByRole('button',{name:'向右',exact:true}),1);
 const jump=await point(phone.getByRole('button',{name:'跳跃 A',exact:true}),2);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right,jump]});
 await expect.poll(keys).toEqual(expect.arrayContaining(['39','32']));
 await phone.setViewportSize({width:390,height:844});
 await expect(phone.locator('.fc-stage')).toHaveAttribute('data-layout','rotated-landscape');
 await expect.poll(keys).toHaveLength(0);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await phone.screenshot({path:'artifacts/visual-qa/fc-figma-portrait-fallback.png'});
 await phone.setViewportSize({width:844,height:390});
 await expect(phone.locator('.fc-stage')).toHaveAttribute('data-layout','landscape');
 const right2=await point(phone.getByRole('button',{name:'向右',exact:true}),1);
 const jump2=await point(phone.getByRole('button',{name:'跳跃 A',exact:true}),2);
 const app=await point(switcher,3);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right2,jump2]});
 await expect.poll(keys).toEqual(expect.arrayContaining(['39','32']));
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[right2,jump2,app]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[app]});
 await expect(tablet.getByRole('dialog',{name:'切换应用'})).toBeVisible();
 await expect(tablet.locator('.highlighted')).toContainText('WorkBuddy');
 await phone.getByRole('button',{name:'切换应用',exact:true}).click();
 await expect(tablet.locator('.highlighted')).toContainText('邮件');
 await expect.poll(()=>frame.evaluate(()=>(window as any).__receivedKeys)).toHaveLength(0);
 await expect(phone.locator('.held')).toHaveCount(0);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await switcher.click();
 await expect(tablet.locator('.highlighted')).toContainText('WPS');
 await expect(tablet.locator('.slides-editor')).toBeVisible({timeout:3000});
 expect(errors).toEqual([]);
 await ctx.close();
});
