import type {Page} from '@playwright/test';
async function home(page:Page){for(let i=0;i<4&&!((await page.locator('.tablet').getAttribute('class'))||'').includes('scene-desktop');i++)await page.getByRole('button',{name:'返回',exact:true}).click();}
import {test,expect} from '@playwright/test';
test('sales workflow, phone readback, target lock, presentation and Mario',async({browser})=>{
 const ctx=await browser.newContext({hasTouch:true});const tablet=await ctx.newPage();const phone=await ctx.newPage();await phone.setViewportSize({width:412,height:915});const errors:string[]=[];tablet.on('pageerror',e=>errors.push(e.message));phone.on('pageerror',e=>errors.push(e.message));
 await tablet.goto('/?bridge=5191');await tablet.getByRole('button',{name:'连接设置',exact:true}).click();const pin=(await tablet.locator('.pair-code').innerText()).trim();await phone.goto('/?role=phone&bridge=5191');await phone.getByLabel('平板地址').fill('localhost');await phone.getByLabel('配对码',{exact:true}).fill(pin);await phone.getByRole('button',{name:'连接',exact:true}).click();await expect(phone.getByText('已连接工作台')).toBeVisible();await tablet.locator('.scrim').click({position:{x:15,y:15}});
 await tablet.screenshot({path:'artifacts/desktop.png'});
 await tablet.locator('.demo-apps').getByRole('button',{name:'邮件',exact:true}).click();await tablet.getByRole('button',{name:'回复',exact:true}).first().click();await expect(phone.getByRole('heading',{name:'邮件正文'})).toBeVisible();await phone.getByLabel('手机输入草稿').fill('林悦，您好：30 套设备的方案已整理，预计 10 月 24 日到货。');await phone.getByRole('button',{name:'写入平板'}).click();await expect(tablet.getByLabel('邮件正文')).toHaveValue(/30 套/);await tablet.getByRole('button',{name:'发送',exact:true}).click();await tablet.screenshot({path:'artifacts/mail.png'});
 await home(tablet);await tablet.getByRole('button',{name:'WPS',exact:true}).click();await tablet.getByRole('button',{name:'返回',exact:true}).click();await tablet.getByRole('button',{name:/采购与客户报价.xlsx/}).click();await tablet.getByLabel('B4 · 轻舟 Pro 商务笔记本 · 数量',{exact:true}).click();await phone.getByLabel('手机输入草稿').fill('40');await phone.getByRole('button',{name:'写入平板'}).click();await expect(tablet.getByLabel('B4 · 轻舟 Pro 商务笔记本 · 数量',{exact:true})).toHaveValue('40');
 await phone.getByLabel('手机输入草稿').fill('45');await tablet.getByLabel('B5 · 明境 27 英寸显示器 · 数量',{exact:true}).click();await expect(phone.getByText('平板目标已变化',{exact:true})).toBeVisible();await expect(phone.getByRole('button',{name:'写入平板'})).toBeDisabled();await phone.getByRole('button',{name:/改为当前对象/}).click();await phone.getByRole('button',{name:'写入平板'}).click();await expect(tablet.getByLabel('B5 · 明境 27 英寸显示器 · 数量',{exact:true})).toHaveValue('45');await phone.getByRole('button',{name:'更新汇报数据'}).click();await tablet.screenshot({path:'artifacts/sheet.png'});
 await home(tablet);await tablet.getByRole('button',{name:'WPS',exact:true}).click();await tablet.getByRole('button',{name:'返回',exact:true}).click();await tablet.getByRole('button',{name:/澄星设计采购方案.docx/}).click();await tablet.locator('.word-paragraph').nth(3).click();await phone.getByLabel('手机输入草稿').fill('服务安排：统一配置、现场安装、专属售后联络。');await phone.getByRole('button',{name:'写入平板'}).click();await expect(tablet.locator('.word-paragraph').nth(3)).toContainText('专属售后');await tablet.screenshot({path:'artifacts/word.png'});
 await home(tablet);await tablet.getByRole('button',{name:'WPS',exact:true}).click();await tablet.getByRole('button',{name:'返回',exact:true}).click();await tablet.getByRole('button',{name:/销售进展汇报.pptx/}).click();await tablet.getByRole('button',{name:'放映',exact:true}).click();await phone.getByRole('button',{name:'下一页',exact:true}).click();await expect(tablet.locator('.presentation .slide-copy h1')).toHaveText('办公设备，统一配置');await expect(tablet.getByText('演讲者备注',{exact:true})).toHaveCount(0);await tablet.getByRole('button',{name:'下一页',exact:true}).click();await expect(phone.locator('.present-meta>span')).toHaveText('03 / 06');await phone.screenshot({path:'artifacts/phone-presentation.png'});await tablet.screenshot({path:'artifacts/presentation.png'});
 await tablet.getByRole('button',{name:'退出放映'}).click();await home(tablet);await tablet.locator('.demo-apps').getByRole('button',{name:'天生会画',exact:true}).click();await phone.getByRole('button',{name:'颜色 #356bd8',exact:true}).click();await tablet.getByRole('button',{name:'调色盘',exact:true}).click();await expect(tablet.getByLabel('画笔颜色',{exact:true})).toHaveValue('#356bd8');await tablet.screenshot({path:'artifacts/paint.png'});
 await home(tablet);await tablet.locator('.demo-apps').getByRole('button',{name:'Super Mario',exact:true}).click();await expect(tablet.locator('.game')).toHaveAttribute('data-ready','true',{timeout:15000});await tablet.evaluate(()=>{window.addEventListener('message',e=>{if(e.data?.kind==='mario-state')(window as any).mario=e.data;});});await expect.poll(()=>tablet.evaluate(()=>(window as any).mario?.x)).toBeDefined();const x=await tablet.evaluate(()=>(window as any).mario.x);const cdp=await ctx.newCDPSession(phone);const right=(await phone.getByRole('button',{name:'向右',exact:true}).boundingBox())!,jump=(await phone.getByRole('button',{name:'跳跃 A',exact:true}).boundingBox())!;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:right.x+right.width/2,y:right.y+right.height/2,id:1},{x:jump.x+jump.width/2,y:jump.y+jump.height/2,id:2}]});await expect.poll(()=>tablet.evaluate(()=>(window as any).mario?.keys)).toEqual(['ArrowRight','Space']);await expect.poll(()=>tablet.evaluate(()=>(window as any).mario?.x)).toBeGreaterThan(x);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>tablet.evaluate(()=>(window as any).mario?.keys)).toEqual([]);await tablet.screenshot({path:'artifacts/mario.png'});expect(errors).toEqual([]);await ctx.close();
});
