import {test,expect} from '@playwright/test';
test('WeChat live drafts, editing, direct replies, Hover sheets, switcher and game',async({browser})=>{
 const ctx=await browser.newContext({permissions:['clipboard-read','clipboard-write']});const tablet=await ctx.newPage(),phone=await ctx.newPage();await phone.setViewportSize({width:390,height:844});const errors:string[]=[];for(const p of [tablet,phone])p.on('pageerror',e=>errors.push(e.message));
 await tablet.goto('/?bridge=5191');await tablet.getByRole('button',{name:'连接手机',exact:true}).click();const pin=await tablet.locator('.pair-code').innerText();await tablet.locator('.scrim').click({position:{x:5,y:5}});await phone.goto('/?role=phone&bridge=5191');await phone.getByLabel('平板地址').fill('localhost');await phone.getByLabel('配对码',{exact:true}).fill(pin);await phone.getByRole('button',{name:'连接',exact:true}).click();await expect(phone.getByText('已连接工作台')).toBeVisible();
 await tablet.screenshot({path:'artifacts/visual-qa/desktop-clean-icons.png'});await tablet.getByRole('button',{name:'微信',exact:true}).click();await tablet.locator('.wx-contact').filter({hasText:'陈总'}).click();await tablet.locator('.wx-bubble').filter({hasText:'下周二下午两点'}).click();await expect(phone.locator('blockquote')).toContainText('下周二下午两点');await expect(tablet.locator('.translation-focus')).toBeVisible();await phone.screenshot({path:'artifacts/visual-qa/wechat-phone.png'});await tablet.screenshot({path:'artifacts/visual-qa/wechat-tablet.png'});
 const before=await tablet.locator('.wx-message').count();await phone.locator('.reply-options button').first().click();await expect(tablet.locator('.wx-message')).toHaveCount(before+1);
 await phone.locator('.related-actions button').first().click();await expect(phone.locator('.hover-services .sheet')).toBeVisible();await phone.screenshot({path:'artifacts/visual-qa/hover-calendar.png'});await phone.locator('.hover-services').getByRole('button',{name:'关闭',exact:true}).click();
 await tablet.getByLabel('微信回复输入框').click();const field=phone.getByLabel('手机输入草稿');await field.fill('明天下午两点见👨‍👩‍👧');await expect(tablet.getByLabel('微信回复输入框')).toHaveValue('明天下午两点见👨‍👩‍👧');await expect(tablet.locator('.wx-message')).toHaveCount(before+1);
 await field.press('End');await phone.getByRole('button',{name:'删除',exact:true}).click();await expect(field).toHaveValue('明天下午两点见');await expect(tablet.getByLabel('微信回复输入框')).toHaveValue('明天下午两点见');await phone.getByRole('button',{name:'撤销',exact:true}).click();await expect(field).toHaveValue('明天下午两点见👨‍👩‍👧');await phone.getByRole('button',{name:'重做',exact:true}).click();await expect(field).toHaveValue('明天下午两点见');await phone.getByRole('button',{name:'撤销',exact:true}).click();await expect(field).toHaveValue('明天下午两点见👨‍👩‍👧');await phone.getByRole('button',{name:'全选',exact:true}).click();await phone.getByRole('button',{name:'剪切',exact:true}).click();await expect(field).toHaveValue('');await phone.getByRole('button',{name:'粘贴',exact:true}).click();await expect(field).toHaveValue('明天下午两点见👨‍👩‍👧');await phone.getByRole('button',{name:'发送回复',exact:true}).click();await expect(tablet.locator('.wx-message')).toHaveCount(before+2);await expect(field).toHaveValue('');
 await tablet.locator('.wx-bubble').filter({hasText:'酒店还没订吧'}).click();await phone.locator('.related-actions button').first().click();await expect(phone.locator('.mock-application.is-ready')).toBeVisible({timeout:8000});await phone.screenshot({path:'artifacts/visual-qa/hover-hotel.png'});const hotel=phone.locator('.hotel-result').first();await expect(hotel).toBeVisible();{await hotel.click();await expect(phone.locator('[data-destination-view=hotel-detail]')).toBeVisible();await phone.evaluate(()=>window.dispatchEvent(new Event('native-back')));await expect(phone.locator('[data-destination-view=hotel-results]')).toBeVisible();}await phone.locator('.mock-app-header button').first().click();
 await phone.getByRole('button',{name:'切换应用',exact:true}).click();await expect(tablet.getByRole('dialog',{name:'切换应用'})).toBeVisible();await expect(phone.getByRole('dialog',{name:'切换应用'})).toHaveCount(0);await phone.getByRole('button',{name:'切换应用',exact:true}).click();await expect(tablet.locator('.highlighted')).toContainText('笔记');await expect(tablet.locator('.tablet')).toHaveClass(/scene-notes/,{timeout:2500});await tablet.getByRole('button',{name:'返回',exact:true}).click();await tablet.getByRole('button',{name:'WPS',exact:true}).click();await expect(tablet.locator('.wps-home')).toBeVisible();await tablet.getByRole('button',{name:'新建文字'}).click();await tablet.getByRole('button',{name:'返回',exact:true}).click();await expect(tablet.locator('.wps-home')).toBeVisible();await tablet.getByRole('button',{name:'返回',exact:true}).click();
 await tablet.getByRole('button',{name:'Super Mario',exact:true}).click();await expect(tablet.getByText('关卡 1-1',{exact:true})).toBeVisible({timeout:15000});await phone.setViewportSize({width:844,height:390});await expect(phone.locator('.fc-phone')).toHaveCount(1);await expect.poll(()=>phone.locator('.fc-phone').evaluate(el=>Math.round(el.getBoundingClientRect().height))).toBe(390);await phone.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await phone.screenshot({path:'artifacts/visual-qa/fc-controller.png'});const frame=tablet.frames().find(f=>f.url().includes('mario-classic'))!;await expect.poll(()=>frame.evaluate(()=>(window as any).__marioState?.y)).toBeGreaterThan(140);await tablet.screenshot({path:'artifacts/visual-qa/mario-classic.png'});const right=phone.getByRole('button',{name:'向右',exact:true});await right.hover();await phone.mouse.down();await expect.poll(()=>frame.evaluate(()=>(window as any).__marioState?.keys)).toContain('39');await phone.mouse.up();await expect.poll(()=>frame.evaluate(()=>(window as any).__marioState?.keys)).not.toContain('39');await phone.getByRole('button',{name:'超级玛丽',exact:true}).click();await phone.getByRole('button',{name:'超级玛丽',exact:true}).click();await expect(tablet.locator('.highlighted')).toContainText('WPS');await expect(tablet.locator('.wps-home')).toBeVisible();expect(errors).toEqual([]);await ctx.close();
});
