import {test,expect,type Page} from '@playwright/test';
async function pair(tablet:Page,phone:Page){await tablet.goto('/?bridge=5191');await tablet.getByRole('button',{name:'连接设置',exact:true}).click();const pin=await tablet.locator('.pair-code').innerText();await tablet.locator('.scrim').click({position:{x:5,y:5}});await phone.goto('/?role=phone&bridge=5191');await phone.getByLabel('平板地址').fill('localhost');await phone.getByLabel('配对码',{exact:true}).fill(pin);await phone.getByRole('button',{name:'连接',exact:true}).click();await expect(phone.getByText('已连接工作台')).toBeVisible();}
test('standby home, composer-only read and staged suggestions, stationary voice button and editable transcript adapter',async({browser})=>{
 const context=await browser.newContext();const tablet=await context.newPage(),phone=await context.newPage();await phone.setViewportSize({width:390,height:844});
 await phone.addInitScript(()=>{const Native=window.WebSocket;window.WebSocket=class extends Native{constructor(url:string,protocols?:string|string[]){super(url,protocols);(window as any).__testSocket=this;}};});
 await pair(tablet,phone);await tablet.getByRole('button',{name:'微信',exact:true}).click();await expect(tablet.locator('.wx-message')).toHaveCount(5);await expect(phone.getByLabel('手机待机桌面')).toBeVisible();await expect(phone.locator('.reply-options button')).toHaveCount(0);await tablet.locator('.wx-bubble').first().click();await expect(tablet.locator('.wx-bubble.focused')).toHaveText('早啊');await expect(phone.getByLabel('手机待机桌面')).toBeVisible();await expect(phone.locator('.related-actions button')).toHaveCount(0);
 await tablet.getByLabel('微信回复输入框').click();await expect(tablet.locator('.wx-input-bar')).toHaveClass(/focus-pulse/);await expect(tablet.locator('.wx-bubble.focused')).toHaveCount(0);await expect(phone.getByLabel('手机待机桌面')).toBeVisible();await expect(tablet.locator('.wx-bubble.scanning')).toContainText('会前帮我准备好报价和项目介绍');await expect(phone.locator('.reply-options button')).toHaveCount(0);await expect(phone.locator('.related-actions button')).toHaveCount(3);await expect(phone.locator('.reply-options button')).toHaveCount(2);expect(await phone.locator('.pop-actions button').evaluateAll(els=>els.map(el=>getComputedStyle(el).animationDelay))).toEqual(['0s','0.11s','0.22s','0.33s','0.44s']);await expect(phone.locator('.related-actions button').last()).toHaveCSS('opacity','1');
 await phone.screenshot({path:'artifacts/visual-qa/wechat-revision-phone.png'});await tablet.screenshot({path:'artifacts/visual-qa/wechat-revision-tablet.png'});
 const field=phone.getByLabel('手机输入草稿');await field.fill('草稿保留');await expect(tablet.getByLabel('微信回复输入框')).toHaveValue('草稿保留');await phone.locator('.reply-options button').first().click();await expect(tablet.locator('.wx-message')).toHaveCount(6);await expect(field).toHaveValue('草稿保留');
 await phone.evaluate(()=>{const w=window as any;w.MobileNative={send:(s:string)=>{w.__testSocket.send(s);return 'sent';},startRecognition:(id:string)=>{w.__speechId=id;window.dispatchEvent(new CustomEvent('native-speech',{detail:{sessionId:id,type:'start'}}));},stopRecognition:(id:string)=>{for(const [type,text] of [['final','明天下午两点开会'],['complete','']])window.dispatchEvent(new CustomEvent('native-speech',{detail:{sessionId:id,type,text}}));},cancelRecognition:()=>{}};});
 const hold=phone.getByRole('button',{name:'按住说话',exact:true}),before=(await hold.boundingBox())!;await hold.hover();await phone.mouse.down();await expect(phone.getByRole('button',{name:'松开结束',exact:true})).toBeVisible();expect((await phone.locator('.hold-voice').boundingBox())!.y).toBe(before.y);await phone.mouse.up();await expect(phone.locator('.polish button')).toHaveCount(3);await expect(phone.locator('.polish')).toContainText('AI润色');expect((await hold.boundingBox())!.y).toBe(before.y);await expect(field).toHaveValue(/明天下午两点开会/);await expect(tablet.getByLabel('微信回复输入框')).toHaveValue(/明天下午两点开会/);await phone.getByRole('button',{name:'礼貌',exact:true}).click();await expect(field).toHaveValue(/^好的/);await phone.getByRole('button',{name:'撤销',exact:true}).click();await expect(field).not.toHaveValue(/^好的/);await phone.screenshot({path:'artifacts/visual-qa/wechat-voice-polish-adapter.png'});
 await phone.locator('.related-actions button').nth(2).click();await expect(phone.locator('.mock-application.is-ready')).toBeVisible();await expect(phone.locator('.mock-document-body')).toContainText('澄星设计');await expect(phone.locator('.mock-document-body')).not.toContainText('汽车业务');await phone.locator('.mock-app-header button').first().click();await expect(field).toHaveValue(/明天下午两点开会/);
 for(const [name,text] of [['老婆','拙政园'],['Alex','sample fee'],['一家人','小盆']]){
  await tablet.locator('.wx-contact').filter({hasText:name}).click();await expect(phone.getByLabel('手机待机桌面')).toBeVisible();await tablet.getByLabel('微信回复输入框').click();await expect(phone.locator('blockquote')).toContainText(text);await expect.poll(()=>phone.locator('.related-actions button').count()).toBeGreaterThan(0);
 }
 await tablet.getByRole('button',{name:'返回',exact:true}).click();await expect(tablet.getByRole('button',{name:'微信',exact:true})).toBeVisible();await tablet.getByRole('button',{name:'微信',exact:true}).click();await expect(tablet.locator('.wx-message')).not.toHaveCount(0);await expect(tablet.locator('.wx-app>section>header')).toContainText('陈总');await expect(tablet.locator('.wx-empty')).toHaveCount(0);
 await context.close();
});
test('presentation Figma controls, live pointer adapter, page ink and release on switch',async({browser})=>{
 const context=await browser.newContext();const tablet=await context.newPage(),phone=await context.newPage();await phone.setViewportSize({width:390,height:844});await phone.addInitScript(()=>{const Native=window.WebSocket;window.WebSocket=class extends Native{constructor(url:string,protocols?:string|string[]){super(url,protocols);(window as any).__testSocket=this;}};});await pair(tablet,phone);
 await tablet.getByRole('button',{name:'WPS',exact:true}).click();await expect(tablet.locator('.slides-editor')).toBeVisible();await expect(phone.locator('.present-meta>span')).toHaveText('01 / 06');await expect(phone.locator('.present-meta time')).toHaveText('00:00');await phone.getByRole('button',{name:'开始放映',exact:true}).click();await expect(tablet.locator('.presentation')).toBeVisible();await expect(phone.locator('.present-meta>span')).toHaveText('01 / 06');await phone.evaluate(()=>document.fonts.ready);expect((await phone.locator('.present-notes p').innerText()).length).toBeGreaterThan(250);await phone.screenshot({path:'artifacts/visual-qa/presentation-figma-phone.png'});
 expect(await phone.locator('.presentation-glass img').evaluateAll(els=>els.every(el=>(el as HTMLImageElement).complete&&(el as HTMLImageElement).naturalWidth>0&&Math.abs((el as HTMLElement).offsetWidth-(el as HTMLImageElement).naturalWidth)<1&&Math.abs((el as HTMLElement).offsetHeight-(el as HTMLImageElement).naturalHeight)<1))).toBe(true);
 await phone.getByRole('button',{name:'下一页',exact:true}).click();await expect(tablet.locator('.presentation-controls')).toContainText('2 / 6');await tablet.getByRole('button',{name:'下一页',exact:true}).click();await expect(phone.locator('.present-meta>span')).toHaveText('03 / 06');await expect(tablet.locator('.presentation')).not.toContainText('演讲备注');await expect(phone.locator('.present-notes')).toHaveCSS('height','536px');await expect(phone.locator('.present-tools button')).toHaveCount(4);await phone.getByRole('button',{name:'实时字幕',exact:true}).click();await expect(phone.locator('.present-state')).toContainText('实时字幕需在手机应用中开启');
 await phone.evaluate(()=>{const w=window as any;w.MobileNative={send:(s:string)=>{w.__testSocket.send(s);return 'sent';},startRecognition:(id:string)=>{w.__captionId=id;return 'starting';},cancelRecognition:()=>{},presentationMotion:(id:string,op:string)=>{if(op==='start'){w.__motion=id;w.__angle=0;w.__timer=setInterval(()=>window.dispatchEvent(new CustomEvent('native-motion',{detail:{id,type:'sample',x:0,y:0,z:Math.sin(w.__angle),w:Math.cos(w.__angle)}})),40);}if(op==='stop')clearInterval(w.__timer);return 'starting';}};});
 await phone.getByRole('button',{name:'激光笔',exact:true}).click();await expect(tablet.locator('.presentation-laser')).toBeVisible();await phone.evaluate(()=>(window as any).__angle=.15);await expect.poll(()=>tablet.locator('.presentation-laser').getAttribute('style')).not.toContain('left: 50%');await phone.getByRole('button',{name:'激光笔',exact:true}).click();await expect(tablet.locator('.presentation-laser')).toHaveCount(0);
 await phone.getByRole('button',{name:'画笔',exact:true}).click();await expect(phone.locator('.present-notes')).toHaveCSS('height','360px');await expect(tablet.getByLabel('画笔悬停',{exact:true})).toBeVisible();await expect(tablet.locator('.presentation-ink polyline')).toHaveCount(0);const hold=phone.getByRole('button',{name:'按住绘制',exact:true});
 await expect(phone.locator('.present-hold')).toHaveCSS('width','168px');await expect(phone.locator('.present-hold')).toHaveCSS('height','168px');await expect(phone.locator('.present-palette')).toHaveCSS('width','168px');await expect(phone.locator('.present-palette')).toHaveCSS('height','168px');
 const notes=phone.locator('.present-notes>div');await notes.evaluate(el=>el.scrollTop=el.scrollHeight);expect(await notes.evaluate(el=>el.scrollTop)).toBeGreaterThan(0);await expect(phone.locator('.present-hold')).toHaveCSS('top','576px');await expect(phone.locator('.present-palette')).toHaveCSS('top','576px');await notes.evaluate(el=>el.scrollTop=0);
 await phone.screenshot({path:'artifacts/wps-square-panel/browser-pen-released.png'});await hold.hover();await phone.mouse.down();await phone.evaluate(()=>(window as any).__angle=.2);await expect(tablet.locator('.presentation-ink polyline')).toHaveCount(1);await expect(hold).toHaveAttribute('aria-pressed','true');await expect(hold).toHaveCSS('background-color','rgb(165, 45, 32)');await expect(hold).toHaveCSS('color','rgb(255, 255, 255)');await phone.screenshot({path:'artifacts/wps-square-panel/browser-pen-pressed.png'});await expect(tablet.getByLabel('正在落笔',{exact:true})).toHaveCSS('height','28px');await expect(tablet.getByLabel('正在落笔',{exact:true})).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await tablet.screenshot({path:'artifacts/visual-qa/pen-held-no-white-box.png'});await phone.mouse.up();await expect(tablet.getByLabel('画笔悬停',{exact:true})).toBeVisible();const stroke=await tablet.locator('.presentation-ink polyline').getAttribute('points');await phone.evaluate(()=>(window as any).__angle=.3);await expect.poll(()=>tablet.getByLabel('画笔悬停',{exact:true}).getAttribute('style')).not.toContain('left: 50%');expect(await tablet.locator('.presentation-ink polyline').getAttribute('points')).toBe(stroke);await phone.screenshot({path:'artifacts/visual-qa/presentation-ink-phone.png'});await tablet.screenshot({path:'artifacts/visual-qa/presentation-ink-adapter.png'});
 await phone.getByRole('button',{name:'下一页',exact:true}).click();await expect(tablet.locator('.presentation-ink polyline')).toHaveCount(0);await phone.getByRole('button',{name:'上一页',exact:true}).click();await expect(tablet.locator('.presentation-ink polyline')).toHaveCount(1);await expect(phone.getByLabel('画笔设置',{exact:true})).toBeVisible();await phone.getByRole('button',{name:'画笔颜色 绿色',exact:true}).click();await phone.getByLabel('笔刷大小',{exact:true}).fill('12');await expect(phone.locator('.present-palette output')).toHaveText('12 px');await expect(phone.getByRole('button',{name:'画笔颜色 绿色',exact:true})).toHaveAttribute('aria-pressed','true');await phone.screenshot({path:'artifacts/visual-qa/presentation-settings-phone.png'});await phone.getByRole('button',{name:'清空本页笔迹',exact:true}).click();await expect(tablet.locator('.presentation-ink polyline')).toHaveCount(0);
 await phone.evaluate(()=>{const w=window as any,send=w.MobileNative.send;w.__rejectedPoints=0;w.MobileNative.send=(raw:string)=>{const msg=JSON.parse(raw);if(msg.command?.type==='present-point'){w.__rejectedPoints++;const ack={kind:'ack',ack:{id:msg.command.id,ok:false,error:'指向已结束',revision:0}};queueMicrotask(()=>{window.dispatchEvent(new CustomEvent('native-message',{detail:ack}));window.dispatchEvent(new CustomEvent('native-message',{detail:ack}));});return 'sent';}return send(raw);};});
 await expect(phone.locator('.toast')).toHaveText('指向已结束');await expect(phone.locator('.toast')).toHaveCount(0,{timeout:6000});expect(await phone.evaluate(()=>(window as any).__rejectedPoints)).toBe(1);
 await expect(phone.locator('.present-volume')).toHaveCount(0);expect(await phone.locator('.presentation-glass img').evaluateAll(els=>els.every(el=>(el as HTMLImageElement).complete&&(el as HTMLImageElement).naturalWidth>0&&Math.abs((el as HTMLElement).offsetWidth-(el as HTMLImageElement).naturalWidth)<1&&Math.abs((el as HTMLElement).offsetHeight-(el as HTMLImageElement).naturalHeight)<1))).toBe(true);
 await phone.getByRole('button',{name:'实时字幕',exact:true}).click();await expect(phone.getByRole('button',{name:'实时字幕',exact:true})).toHaveAttribute('aria-pressed','true');
 await phone.evaluate(()=>window.dispatchEvent(new CustomEvent('native-speech',{detail:{sessionId:(window as any).__captionId,type:'partial',text:'这是浏览器测试转写'}})));await expect(tablet.getByLabel('实时字幕',{exact:true})).toHaveText('这是浏览器测试转写');await phone.getByRole('button',{name:'下一页',exact:true}).click();await expect(tablet.getByLabel('实时字幕',{exact:true})).toHaveText('这是浏览器测试转写');
 await phone.getByRole('button',{name:'退出全屏',exact:true}).click();await expect(tablet.locator('.slides-editor')).toBeVisible();await expect(phone.locator('.presentation-glass')).toBeVisible();await expect(phone.getByRole('button',{name:'实时字幕',exact:true})).toHaveAttribute('aria-pressed','false');await phone.getByRole('button',{name:'开始放映',exact:true}).click();await expect(tablet.locator('.presentation')).toBeVisible();await expect(tablet.getByLabel('实时字幕',{exact:true})).toHaveCount(0);
 await phone.getByRole('button',{name:'切换应用',exact:true}).click();await expect(tablet.locator('.highlighted')).toContainText('微信');await expect(tablet.locator('.tablet')).toHaveClass(/scene-wechat/);await context.close();
});
