import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUp,ArrowDown} from 'lucide-react';
import {command,useRuntime} from './runtime';
export function FcController(){const r=useRuntime(),s=r.state;const held=useRef(new Map<number,string>()),[pressed,setPressed]=useState<string[]>([]),reset=useRef<ReturnType<typeof setTimeout>|null>(null);
 const release=()=>{held.current.clear();setPressed([]);command('release');};
 const publish=()=>{const keys=[...new Set(held.current.values())];setPressed(keys);command('game-keys',keys);};
 useEffect(()=>{const tick=setInterval(()=>{if(held.current.size)publish();},150);const hide=()=>{if(document.hidden)release();};window.addEventListener('blur',release);document.addEventListener('visibilitychange',hide);return()=>{clearInterval(tick);if(reset.current)clearTimeout(reset.current);window.removeEventListener('blur',release);document.removeEventListener('visibilitychange',hide);held.current.clear();command('release');};},[]);
 useEffect(()=>{if(s.gamePaused||!r.connected){held.current.clear();setPressed([]);}},[s.gamePaused,r.connected]);
 const props=(key:string)=>({className:pressed.includes(key)?'held':'',onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);held.current.set(e.pointerId,key);publish();},onPointerUp:(e:React.PointerEvent)=>{held.current.delete(e.pointerId);publish();},onPointerCancel:(e:React.PointerEvent)=>{held.current.delete(e.pointerId);publish();},onLostPointerCapture:(e:React.PointerEvent)=>{if(held.current.delete(e.pointerId))publish();}});
 return <main className="fc-phone"><header className="glass-status"><span><i className={r.connected?'online-dot':'offline-dot'}/>{r.connected?'已连接':'连接已断开'}</span><button onClick={()=>{held.current.clear();setPressed([]);if(reset.current)clearTimeout(reset.current);command('switch-step');}}>超级玛丽</button><span className="fc-state">{s.gamePaused?'已暂停':''}</span></header><div className="fc-body"><div className="fc-dpad"><button className="up" aria-label="方向上"><ArrowUp/></button><button aria-label="向左" {...props('ArrowLeft')}><ArrowLeft/></button><span/><button aria-label="向右" {...props('ArrowRight')}><ArrowRight/></button><button className="down" aria-label="方向下"><ArrowDown/></button></div><div className="fc-middle"><div className="fc-slats"><i/><i/><i/></div><div><button aria-label="长按重新开始" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);reset.current=setTimeout(()=>{release();command('game-reset');reset.current=null;},1000);}} onPointerUp={()=>{if(reset.current)clearTimeout(reset.current);}} onPointerCancel={()=>{if(reset.current)clearTimeout(reset.current);}}>SELECT</button><button onClick={()=>{release();command('game-pause',!s.gamePaused);}}>START</button></div></div><div className="fc-actions"><button aria-label="加速 B" {...props('Shift')}>B</button><button aria-label="跳跃 A" {...props('Space')}>A</button></div></div>{r.toast&&<div role="status" className="toast">{r.toast}</div>}</main>;
}
