import {PhoneWorkBuddyHub} from './phone-workbuddy-hub';
import {PhoneWorkBuddy} from './phone-workbuddy';
import {PhoneHome} from './phone-home';
import {PresentationPhone} from './phone-presentation';
import {PhoneWeChat,SwitchButton} from './phone-wechat';
import {FcController} from './phone-game';
import {useEffect,useRef,useState} from 'react';import * as I from 'lucide-react';
import {apps,type Target} from '../../../packages/core/model';import {command,useRuntime,toast,uid} from './runtime';import {Icon} from './tablet';import {AppIcon} from './desktop';
function LegacyPhone({onWorkBuddy}:{onWorkBuddy?:()=>void}){const r=useRuntime(),s=r.state;const [draft,setDraft]=useState(''),[anchor,setAnchor]=useState<Target|null>(null),[dirty,setDirty]=useState(false),[speech,setSpeech]=useState('idle'),[speechError,setSpeechError]=useState(''),[online,setOnline]=useState(false),[clock,setClock]=useState(Date.now());const session=useRef(''),speechBase=useRef(''),speechOriginal=useRef(''),held=useRef(new Set<string>()),editVersion=useRef(0),latest=useRef(s);latest.current=s;const active=apps.find(a=>a[0]===s.app);const changed=!!anchor&&(anchor.id!==s.target?.id||anchor.revision!==s.target?.revision||anchor.app!==s.app);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!dirty&&speech==='idle'){setAnchor(s.target);setDraft(s.target?.value||'');}},[s.target?.id,s.target?.revision,dirty,speech]);
 useEffect(()=>{const f=(e:Event)=>{const d=(e as CustomEvent).detail;if(!session.current||d.sessionId!==session.current)return;if(d.type==='partial'||d.type==='final'){editVersion.current++;setDraft(speechBase.current+d.text);setDirty(true);}if(d.type==='start')setSpeech('recording');if(d.type==='complete'){setSpeech('idle');session.current='';}if(d.type==='error'){setSpeech('idle');setSpeechError(d.message||'语音识别不可用');session.current='';}};window.addEventListener('native-speech',f);return()=>window.removeEventListener('native-speech',f);},[]);
 const release=()=>{held.current.clear();command('release');};
 useEffect(()=>{if(!r.connected)held.current.clear();},[r.connected]);
 useEffect(()=>{const timer=setInterval(()=>{if(held.current.size)command('game-keys',[...held.current]);},150);const blur=()=>release();window.addEventListener('blur',blur);const hidden=()=>{if(document.hidden){release();window.MobileNative?.cancelRecognition(session.current);session.current='';setSpeech('idle');}};document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(timer);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);};},[]);
 useEffect(()=>{held.current.clear();},[s.app,s.gamePaused]);
 function record(){if(!anchor||!['text','number'].includes(anchor.kind)){toast('请先在平板选择输入位置');return;}if(!window.MobileNative){setSpeechError('内置语音需在手机 HAP 中使用');return;}if(speech!=='idle'){setSpeech('finishing');window.MobileNative.stopRecognition(session.current);return;}session.current=uid();speechOriginal.current=draft;speechBase.current=draft?draft+'\n':'';setDirty(true);setSpeechError('');setSpeech('starting');window.MobileNative.startRecognition(session.current,online);}
 async function submit(){if(!anchor||changed)return;const version=editVersion.current;const submitted=anchor;const result=await command('input',draft,{app:anchor.app,targetId:anchor.id,targetRevision:anchor.revision});if(result.ok){if(latest.current.target?.id===submitted.id&&latest.current.target.app===submitted.app&&latest.current.target.revision===result.revision)setAnchor(latest.current.target);if(editVersion.current===version)setDirty(false);toast('已写入平板');}}
 const bind=()=>{setAnchor(s.target);setDirty(true);};
 const keyProps=(key:string)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);held.current.add(key);command('game-keys',[...held.current]);},onPointerUp:()=>{held.current.delete(key);command('game-keys',[...held.current]);},onPointerCancel:()=>{held.current.delete(key);command('game-keys',[...held.current]);},onLostPointerCapture:()=>{held.current.delete(key);command('game-keys',[...held.current]);}});
 return <main className={'phone '+(s.app==='mario'?'phone-game':'')}> {r.connected&&<><section className="target-summary"><span className="target-icon" style={{background:active?.[2]||'#758194'}}><AppIcon id={s.app} size={48}/></span><div><small>{active?.[1]||'桌面'}</small><h2>{s.presenting?`销售进展汇报 · 第 ${s.slide+1} 页`:s.target?.label||'选择一个对象'}</h2></div>{s.target&&<I.Crosshair size={20}/>}</section>
 {s.app==='desktop'&&onWorkBuddy&&<button className="primary" onClick={onWorkBuddy}>在工作台打开 WorkBuddy</button>}
 {s.app==='desktop'&&<div className="phone-apps">{apps.filter(a=>['mail','wps','wechat','doubao','notes','paint','mario'].includes(a[0])).map(a=><button key={a[0]} onClick={()=>command('open',a[0])}><span style={{background:a[2]}}><AppIcon id={a[0]} size={42}/></span>{a[1]}</button>)}</div>}
 {s.app==='slides'&&<section className="presentation-phone"><div className="present-mode"><b>{s.presenting?'正在放映':'编辑演示文稿'}</b><button onClick={()=>command('present',!s.presenting)}>{s.presenting?'结束放映':'开始放映'}<I.Play size={15}/></button></div>{s.presenting&&<><div className="slide-counter"><span>{String(s.slide+1).padStart(2,'0')}</span><small>/ 06</small><time>{new Date(Math.max(0,clock-s.startedAt)).toISOString().slice(14,19)}</time></div><h2>{s.slides[s.slide].title}</h2><div className="private-notes"><span><I.LockKeyhole size={13}/>演讲者备注</span><p>{s.slides[s.slide].notes}</p></div></>}<div className="slide-arrows"><button disabled={s.slide===0} onClick={()=>command('slide',s.slide-1)}><I.ChevronLeft size={32}/>上一页</button><button disabled={s.slide===5} onClick={()=>command('slide',s.slide+1)}>下一页<I.ChevronRight size={32}/></button></div><div className="slide-dots">{s.slides.map((x,i)=><button key={i} className={i===s.slide?'active':''} aria-label={`跳至第 ${i+1} 页`} onClick={()=>command('slide',i)}>{i+1}</button>)}</div></section>}
 {['paint','notes'].includes(s.app)&&<section className="phone-tools"><header><h3>画笔工具</h3><button onClick={()=>command('undo-stroke')}><I.Undo2 size={20}/>撤销</button></header><div className="color-swatches">{['#ed5b94','#1e293b','#356bd8','#e8b84a','#60aa8c','#9e6bd8'].map(c=><button key={c} aria-label={'颜色 '+c} style={{background:c}} className={s.color===c?'chosen':''} onClick={()=>command('color',c)}/>)}<input aria-label="自定义颜色" type="color" value={s.color} onChange={e=>command('color',e.target.value)}/></div><label className="brush-label">笔刷大小 <b>{s.brush} px</b></label><input aria-label="手机笔刷大小" className="wide-slider" type="range" min="1" max="40" value={s.brush} onChange={e=>command('brush',Number(e.target.value))}/><div className="tool-pair"><button className={!s.eraser?'active':''} onClick={()=>command('eraser',false)}><I.Paintbrush/>画笔</button><button className={s.eraser?'active':''} onClick={()=>command('eraser',true)}><I.Eraser/>橡皮擦</button></div></section>}
 {s.app==='mario'&&<section className="gamepad"><div className="gamepad-title"><span>SUPER MARIO</span><div><button onClick={()=>{release();command('game-pause',!s.gamePaused);}}>{s.gamePaused?<I.Play/>:<I.Pause/>}</button><button aria-label="重新开始游戏" onClick={()=>{release();command('game-reset');}}><I.RotateCcw/></button></div></div><div className="gamepad-controls"><div className="dpad"><button aria-label="向左" {...keyProps('ArrowLeft')}><I.ChevronLeft size={52}/></button><button aria-label="向右" {...keyProps('ArrowRight')}><I.ChevronRight size={52}/></button></div><button aria-label="跳跃" className="jump" {...keyProps('Space')}>A<small>跳跃</small></button></div></section>}
 {['bilibili','douyin','red','read'].includes(s.app)&&<section className="media-phone"><div className="transport"><button onClick={()=>command('media-next',-1)}><I.SkipBack/></button><button className="play" onClick={()=>command('play',!s.playing)}>{s.playing?<I.Pause/>:<I.Play/>}</button><button onClick={()=>command('media-next',1)}><I.SkipForward/></button></div>{s.app!=='read'&&<input aria-label="手机播放进度" className="wide-slider" type="range" value={s.progress} onChange={e=>command('seek',Number(e.target.value))}/>}</section>}
 {!s.presenting&&s.app!=='mario'&&anchor&&['text','number'].includes(anchor.kind)&&<section className="phone-editor"><header><span>{anchor.kind==='number'?'数值输入':'文字与语音'}</span><button onClick={()=>command('undo')}><I.Undo2 size={17}/>撤销</button></header>{changed&&<div className="target-changed"><b>平板目标已变化</b><span>草稿保留在 {anchor.label}</span>{s.target&&<button onClick={bind}>改为当前对象：{s.target.label}</button>}</div>}<textarea aria-label="手机输入草稿" inputMode={anchor.kind==='number'?'decimal':'text'} value={draft} onChange={e=>{editVersion.current++;setDraft(e.target.value);setDirty(true);}} placeholder="输入内容…"/>{anchor.kind==='number'&&<div className="number-tools"><button onClick={()=>{editVersion.current++;setDraft(String((Number(draft)||0)-1));setDirty(true);}}>−1</button><button onClick={()=>{editVersion.current++;setDraft(String((Number(draft)||0)+1));setDirty(true);}}>＋1</button></div>}
 <div className="speech-controls"><button className={speech!=='idle'?'recording':''} disabled={speech==='finishing'||changed} onClick={record}>{speech==='idle'?<I.Mic size={22}/>:<I.Square size={19}/>}<span>{speech==='idle'?'语音输入':speech==='recording'?'停止录音':speech==='starting'?'正在启动…':'正在完成…'}</span></button>{speech!=='idle'&&<button onClick={()=>{window.MobileNative?.cancelRecognition(session.current);session.current='';setSpeech('idle');editVersion.current++;setDraft(speechOriginal.current);}}>取消</button>}</div>{speechError&&<div className="speech-error"><p>{speechError}</p>{window.MobileNative&&!online&&<button onClick={()=>{setOnline(true);setSpeechError('已选择系统在线识别，再次点击语音输入开始');}}>使用系统在线识别</button>}</div>}{online&&<small className="online-speech">系统在线识别</small>}
 <button className="primary send-to-tablet" disabled={changed||speech!=='idle'||!dirty} onClick={submit}>写入平板<I.ArrowUpRight size={20}/></button>{s.app==='word'&&<div className="format-tools"><button onClick={()=>command('format','bold',{targetId:anchor.id,targetRevision:anchor.revision})}><I.Bold size={18}/>加粗</button><button onClick={()=>command('format','normal',{targetId:anchor.id,targetRevision:anchor.revision})}>正文</button></div>}</section>}
 {s.app==='sheet'&&<button className="refresh-report" onClick={()=>command('report-refresh').then(a=>a.ok&&toast('汇报数据已更新'))}><I.RefreshCw size={19}/>更新汇报数据</button>}
 {s.app!=='desktop'&&<footer className="phone-footer"><button onClick={()=>command('open','desktop')}><I.Grid2X2 size={17}/>工作台</button><span>{r.status}</span></footer>}</>}
 {r.toast&&<div className="toast" role="status">{r.toast}</div>}
 </main>;
}

export function Phone(){
 const r=useRuntime();
 const [workbuddyOpen,setWorkbuddyOpen]=useState(false);
 useEffect(()=>{if(r.state.app!=='workbuddy')setWorkbuddyOpen(false);},[r.state.app]);
 const enterWorkBuddy=async()=>{if(r.state.app!=='workbuddy'){const ack=await command('open','workbuddy');if(!ack.ok)return;}setWorkbuddyOpen(true);};
 if(workbuddyOpen&&r.state.app==='workbuddy')return <PhoneWorkBuddyHub onClose={()=>setWorkbuddyOpen(false)}/>;
 if(!r.connected&&!['slides','mario'].includes(r.state.app))return <PhoneHome/>;
 if(r.state.app==='workbuddy')return r.connected&&r.state.target?.id.startsWith('wb:')?<PhoneWorkBuddy key={r.state.target.id} onOverview={()=>setWorkbuddyOpen(true)}/>:<PhoneHome onWorkBuddy={enterWorkBuddy}/>;
 if(r.state.app==='slides')return <PresentationPhone/>;
 if(r.state.app==='wechat')return r.connected&&r.state.chat.activation?.phase==='ready'?<PhoneWeChat/>:<PhoneHome onWorkBuddy={enterWorkBuddy} workbuddyLabel="在工作台打开 WorkBuddy"/>;
 if(r.state.app==='mario')return <FcController/>;
 return <><LegacyPhone onWorkBuddy={enterWorkBuddy}/>{r.connected&&<div className='global-phone-switch'><SwitchButton/></div>}</>;
}
