import {WorkBuddy} from './workbuddy';
import {PresentationOverlay} from './presentation-overlay';
import './phone-presentation.css';
import {WeChat} from './wechat';
import {demoApps} from '../../../packages/core/interactions';
import {MailReplica,ChatReplica,AssistantReplica,MediaReplica} from './replica-apps';
import {Desktop,AppIcon} from './desktop';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import * as I from 'lucide-react';
import {apps,totals,money,type AppId,type State,type Target,type Stroke} from '../../../packages/core/model';
import {navigateBack,command,choose,input,useRuntime,toast} from './runtime';
export function Icon({name,size=22}:{name:string;size?:number}){const icons:Record<string,typeof I.Mail>={Mail:I.Mail,Table2:I.Table2,FileText:I.FileText,Presentation:I.Presentation,MessageCircle:I.MessageCircle,NotebookPen:I.NotebookPen,Paintbrush:I.Paintbrush,Sparkles:I.Sparkles,Bot:I.Bot,Orbit:I.Orbit,Tv:I.Tv,Music2:I.Music2,Heart:I.Heart,BookOpen:I.BookOpen,Gamepad2:I.Gamepad2,AppWindow:I.AppWindow,Monitor:I.Monitor,Inbox:I.Inbox,Star:I.Star,Send:I.Send};const C=icons[name]||I.Square;return <C size={size} strokeWidth={1.8}/>;}
export function Button({children,onClick,title,active=false}:{children:ReactNode;onClick:()=>void;title?:string;active?:boolean}){return <button title={title} aria-label={title} className={active?'active':''} onClick={onClick}>{children}</button>;}
const open=(a:AppId)=>command('open',a);
export function Tablet(){const r=useRuntime(),s=r.state;const [recent,setRecent]=useState(false);const app=apps.find(a=>a[0]===s.app);useEffect(()=>{const back=(e:Event)=>{if(e.defaultPrevented)return;if(recent){e.preventDefault();setRecent(false);}};window.addEventListener('app-back',back);return()=>window.removeEventListener('app-back',back);},[recent]);return <div className={'tablet scene-'+s.app+' '+(s.presenting?'presenting':'')}>
 {!s.presenting&&s.app!=='mario'&&s.app!=='workbuddy'&&<div className="systembar"><span>{new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span><span className="system-title">{app?.[1]||''}</span><I.Wifi size={16}/><I.BatteryFull size={21}/></div>}
 {s.app==='desktop'?<Desktop/>:<><div className="windowbar" hidden={s.presenting||s.app==='mario'||s.app==='workbuddy'}><Button title="返回" onClick={navigateBack}><I.ChevronLeft size={20}/></Button><span className="app-label" style={{color:app?.[2]}}><AppIcon id={s.app} size={20}/>{app?.[1]}</span><span className="window-dots">•••</span><Button title="最近应用" onClick={()=>setRecent(!recent)}><I.LayoutGrid size={18}/></Button></div><div className="application">
 {s.app==='wps'?<WpsHome s={s}/>:s.app==='mail'?<MailReplica s={s}/>:s.app==='sheet'?<Sheet s={s}/>:s.app==='word'?<Word s={s}/>:s.app==='slides'?<Slides s={s}/>:s.app==='paint'||s.app==='notes'?<Drawing s={s}/>:s.app==='mario'?<Mario s={s}/>:s.app==='wechat'?<WeChat s={s}/>:s.app==='workbuddy'?<WorkBuddy s={s}/>:['doubao','xiaoyi'].includes(s.app)?<AssistantReplica s={s}/>:<MediaReplica s={s}/>}</div></>}
 {s.switcher&&<div className='switcher-scrim' onClick={()=>command('switch-cancel')}><section className='app-switcher' role='dialog' aria-label='切换应用' onClick={e=>e.stopPropagation()}><header><h2>切换应用</h2><button aria-label='取消切换' onClick={()=>command('switch-cancel')}><I.X/></button></header><div>{demoApps.map((id,i)=><button key={id} aria-label={apps.find(a=>a[0]===id)?.[1]} className={s.switcher?.index===i?'highlighted':''} onClick={()=>open(id)}><AppIcon id={id} size={72}/><span>{apps.find(a=>a[0]===id)?.[1]}</span></button>)}</div></section></div>}
 {!s.presenting&&s.app!=='mario'&&s.app!=='workbuddy'&&<button aria-label="主页" className="home-indicator" onClick={()=>open('desktop')}/>}
 {recent&&<div className="recent-overlay"><header><h2>最近应用</h2><Button onClick={()=>setRecent(false)}><I.X/></Button></header><div>{s.recent.map(a=><button key={a} onClick={()=>{open(a);setRecent(false);}}><AppIcon id={a} size={64}/><strong>{apps.find(x=>x[0]===a)?.[1]}</strong></button>)}</div></div>}
 {r.toast&&<div role="status" className="toast">{r.toast}</div>}
 </div>;}
export function TargetField({id,label,value,kind='text',multiline=false}:{id:string;label:string;value:string;kind?:Target['kind'];multiline?:boolean}){const {state:s}=useRuntime();const active=s.target?.id===id;const edit=()=>choose(id,label,kind,value);return <div className={'target-field '+(active?'selected':'')} onClick={edit}><label>{label}</label>{multiline?<textarea aria-label={label} value={value} onFocus={edit} onChange={e=>input(e.target.value)}/>:<input aria-label={label} value={value} onFocus={edit} onChange={e=>input(e.target.value)}/>}</div>;}
function Ribbon({type,s}:{type:'sheet'|'word'|'slides';s:State}){return <><div className={'office-tabs '+type}><span className="wps-logo">WPS</span><b>{s.officeFiles.find(f=>f.id===s.officeFile&&f.kind===type)?.name||(type==='sheet'?'采购与客户报价.xlsx':type==='word'?'澄星设计采购方案.docx':'销售进展汇报.pptx')}</b><span className="saved"><I.Check size={14}/>已保存到本机</span></div><div className="ribbon-tabs"><b>开始</b><span>插入</span><span>{type==='sheet'?'公式':'设计'}</span><span>视图</span><span>审阅</span><span>工具</span><button onClick={()=>command('report-refresh').then(()=>toast('汇报数据已更新'))}><I.RefreshCw size={14}/>更新汇报数据</button>{type==='slides'&&<button className="primary" onClick={()=>command('present',true)}><I.Play size={15}/>放映</button>}</div><div className="ribbon"><Button title="撤销" onClick={()=>command('undo')}><I.Undo2/></Button><span className="ribbon-divider"/><span className="font-select">微软雅黑 <I.ChevronDown size={12}/></span><span>12 <I.ChevronDown size={12}/></span><Button title="加粗" onClick={()=>{if(s.target)command('format','bold',{targetId:s.target.id,targetRevision:s.target.revision});}}><I.Bold size={18}/></Button><Button title="恢复正文格式" onClick={()=>{if(s.target)command('format','normal',{targetId:s.target.id,targetRevision:s.target.revision});}}><I.Type size={18}/></Button><I.AlignLeft size={18}/><I.AlignCenter size={18}/><I.List size={18}/><span className="ribbon-divider"/><I.PaintBucket size={18}/><I.Table2 size={18}/><span className="ribbon-hint">{s.target?.label||'请选择内容'}</span></div></>;}
function Sheet({s}:{s:State}){const result=totals(s.products);const fields=['quantity','cost','price','discount'] as const;return <div className="office sheet-office"><Ribbon type="sheet" s={s}/><div className="formula"><span>{s.target?.id.startsWith('cell:')?s.target.label.split(' · ')[0]:'A1'}</span><b>ƒx</b><input aria-label="公式栏" value={s.target?.value??''} onChange={e=>input(e.target.value)} disabled={!s.target?.id.startsWith('cell:')}/></div><div className="sheet-scroll"><table className="spreadsheet"><thead><tr><th></th>{'ABCDEFGH'.split('').map(x=><th key={x}>{x}</th>)}</tr></thead><tbody><tr><th>1</th><td colSpan={8} className="sheet-title">澄星设计 · 采购与客户报价</td></tr><tr><th>2</th><td colSpan={8} className="sheet-subtitle">锐行办公　|　客户经理：陈朗　|　报价版本 V{s.reportRevision+1}</td></tr><tr><th>3</th>{['产品名称','数量','采购单价','销售单价','折扣 %','采购成本','客户报价','毛利'].map(x=><td className="table-heading" key={x}>{x}</td>)}</tr>{s.products.map((p,i)=>{const t=totals([p]);return <tr key={p.id}><th>{i+4}</th><td>{p.name}</td>{fields.map((f,j)=>{const id=`cell:${i}:${f}`,value=String(p[f]),label=`${'BCDE'[j]}${i+4} · ${p.name} · ${['数量','采购单价','销售单价','折扣'][j]}`;return <td className={s.target?.id===id?'cell-selected':''} key={f} onClick={()=>choose(id,label,'number',value)}><input aria-label={label} inputMode="decimal" value={value} onFocus={()=>choose(id,label,'number',value)} onChange={e=>input(e.target.value)}/></td>;})}<td>{money(t.cost)}</td><td>{money(t.revenue)}</td><td>{money(t.profit)}</td></tr>;})}<tr className="sum-row"><th>7</th><td>合计</td><td>{s.products.reduce((x,p)=>x+p.quantity,0)}</td><td/><td/><td/><td>{money(result.cost)}</td><td>{money(result.revenue)}</td><td>{money(result.profit)}</td></tr><tr><th>8</th><td>综合毛利率</td><td>{result.margin.toFixed(1)}%</td><td colSpan={6}>客户预算：¥200,000.00</td></tr>{Array.from({length:12},(_,i)=><tr key={i}><th>{i+9}</th>{Array.from({length:8},(_,j)=><td key={j}/>)}</tr>)}</tbody></table></div><footer className="sheet-footer"><b>采购报价</b><span>＋</span><span className="grow"/><span>求和：{money(result.revenue)}</span><span>100%</span></footer></div>;}
function Word({s}:{s:State}){const t=totals(s.reportProducts);return <div className="office"><Ribbon type="word" s={s}/><div className="document-scroll"><div className="ruler">1　　　　2　　　　3　　　　4　　　　5　　　　6　　　　7　　　　8</div><article className="word-page"><div className="letterhead">锐行办公 <span>RUIXING OFFICE</span></div>{s.paragraphs.map((p,i)=><div key={i} className={'word-paragraph '+(i===0?'document-title ':'')+(s.target?.id===`paragraph:${i}`?'selected':'')} style={{fontWeight:s.texts[`format:paragraph:${i}`]==='bold'?700:undefined}} onClick={()=>choose(`paragraph:${i}`,`方案 · 第 ${i+1} 段`,'text',p)}>{p}</div>)}<h3>设备与报价</h3><table className="doc-table"><thead><tr><th>产品</th><th>数量</th><th>优惠后报价</th></tr></thead><tbody>{s.reportProducts.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.quantity}</td><td>{money(totals([p]).revenue)}</td></tr>)}</tbody></table><div className="quote-total">方案总报价 <strong>{money(t.revenue)}</strong></div><footer>陈朗 · 锐行办公　　chen.lang@example.com<span>01</span></footer></article></div><footer className="office-status">第 1 页，共 1 页 <span>中文（中国）</span><span>100%</span></footer></div>;}
export function SlideCanvas({s,mini=false}:{s:State;mini?:boolean}){const slide=s.slides[s.slide],t=totals(s.reportProducts);return <div className={'slide-canvas slide-'+s.slide+(mini?' mini':'')}><div className="slide-eyebrow">RUIXING OFFICE <span>澄星设计 / PROJECT UPDATE</span></div><div className="slide-copy"><h1 onClick={()=>!s.presenting&&!mini&&choose(`slide:${s.slide}:title`,'幻灯片标题','text',slide.title)} className={s.target?.id===`slide:${s.slide}:title`?'selected':''}>{slide.title}</h1><p onClick={()=>!s.presenting&&!mini&&choose(`slide:${s.slide}:body`,'幻灯片正文','text',slide.body)} className={s.target?.id===`slide:${s.slide}:body`?'selected':''}>{slide.body}</p></div>{s.slide===0?<div className="slide-orbit"><div/><div/><div/></div>:s.slide===3?<div className="slide-chart"><div><span>客户报价</span><b>{money(t.revenue)}</b><i style={{width:'100%'}}/></div><div><span>采购成本</span><b>{money(t.cost)}</b><i style={{width:`${Math.min(100,t.cost/Math.max(t.revenue,1)*100)}%`}}/></div><div><span>项目毛利</span><b>{money(t.profit)}</b><i style={{width:`${Math.max(2,t.margin)}%`}}/></div></div>:<div className="slide-number">0{s.slide+1}</div>}<footer><span>锐行办公 · 销售进展汇报</span><span>{String(s.slide+1).padStart(2,'0')} / 06</span></footer>{s.presenting&&!mini&&<PresentationOverlay s={s}/>}</div>;}
function Slides({s}:{s:State}){
 useEffect(()=>{const applyVolume=()=>{document.querySelectorAll<HTMLMediaElement>('audio,video').forEach(media=>{media.volume=s.presentation.volume.level/100;media.muted=s.presentation.volume.muted;});};applyVolume();const observer=new MutationObserver(applyVolume);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect();},[s.presentation.volume.level,s.presentation.volume.muted]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')command('slide',s.slide+1);if(e.key==='ArrowLeft')command('slide',s.slide-1);if(e.key==='Escape')command('present',false);};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f);},[s.slide]);if(s.presenting)return <div className="presentation"><button className="presentation-back" aria-label="返回" onClick={navigateBack}><I.ChevronLeft/></button><SlideCanvas s={s}/><div className="presentation-controls"><Button title="退出放映" onClick={()=>command('present',false)}><I.X size={18}/></Button><Button title="上一页" onClick={()=>command('slide',s.slide-1)}><I.ChevronLeft/></Button><span>{s.slide+1} / 6</span><Button title="下一页" onClick={()=>command('slide',s.slide+1)}><I.ChevronRight/></Button></div></div>;return <div className="office"><Ribbon type="slides" s={s}/><div className="slides-editor"><aside className="slide-thumbnails">{s.slides.map((x,i)=><button key={i} className={i===s.slide?'selected':''} onClick={()=>command('slide',i)}><small>{i+1}</small><SlideCanvas s={{...s,slide:i,target:null}} mini/></button>)}</aside><div className="slide-workspace"><SlideCanvas s={s}/><div className="slide-notes"><TargetField id={`slide:${s.slide}:notes`} label="演讲者备注" value={s.slides[s.slide].notes} multiline/></div></div></div><footer className="office-status">幻灯片 {s.slide+1} / 6 <span>主题：锐行办公</span><button onClick={()=>command('present',true)}><I.Play size={16}/>从当前页放映</button></footer></div>;}
function Drawing({s}:{s:State}){
 const ref=useRef<HTMLCanvasElement>(null),current=useRef<Stroke|null>(null),art=useRef<HTMLImageElement|null>(null);const [palette,setPalette]=useState(false),[overview,setOverview]=useState(true),[opacity,setOpacity]=useState(100);const isNotes=s.app==='notes';
 useEffect(()=>{const back=(e:Event)=>{if(palette&&!e.defaultPrevented){e.preventDefault();setPalette(false);}};window.addEventListener('app-back',back);return()=>window.removeEventListener('app-back',back);},[palette]);
 function redraw(){const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d')!;ctx.clearRect(0,0,canvas.width,canvas.height);if(!isNotes&&art.current?.complete)ctx.drawImage(art.current,canvas.width*605/2800,canvas.height*305/1840,canvas.width*1780/2800,canvas.height*1240/1840);for(const st of [...(isNotes?s.noteStrokes:s.strokes),...(current.current?[current.current]:[])]){ctx.beginPath();ctx.strokeStyle=st.eraser?(isNotes?'#eeebd8':'#ffffff'):st.color;ctx.lineWidth=st.size*canvas.width/1400;ctx.lineCap='round';ctx.lineJoin='round';st.points.forEach(([x,y],i)=>i?ctx.lineTo(x*canvas.width,y*canvas.height):ctx.moveTo(x*canvas.width,y*canvas.height));ctx.stroke();}}
 useEffect(()=>{const img=new Image();img.src='./reference-assets/paint-ink.png';img.onload=()=>{art.current=img;redraw();};return()=>{img.onload=null;};},[isNotes]);
 useEffect(()=>{const canvas=ref.current!;const resize=()=>{canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;redraw();};const o=new ResizeObserver(resize);o.observe(canvas);return()=>o.disconnect();},[s.strokes,s.noteStrokes,s.color,s.brush,isNotes]);useEffect(redraw,[s.strokes,s.noteStrokes,isNotes]);
 const pos=(e:React.PointerEvent<HTMLCanvasElement>):[number,number]=>{const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];};
 const brushButton=<Button title="画笔" active={!s.eraser} onClick={()=>command('eraser',false)}><I.Paintbrush/></Button>;
 const eraseButton=<Button title="橡皮擦" active={s.eraser} onClick={()=>command('eraser',true)}><I.Eraser/></Button>;
 return <div className={'drawing drawing-replica '+(isNotes?'notebook':'gopaint')}>
 {isNotes?<><div className="notes-tabs"><button aria-label="返回桌面" onClick={()=>open('desktop')}><I.House/></button><span><I.PanelLeft size={18}/>Unnamed note (3)<I.X size={18}/></span><span>澄星项目会议记录<I.X size={18}/></span><button aria-label="添加文字" onClick={()=>choose('notes-text','笔记文字','text',s.texts['notes-text'])}><I.Plus/></button><button aria-label="页面概览" onClick={()=>setOverview(!overview)}><I.MoreHorizontal/></button></div><div className="notes-toolbar"><Button title="撤销笔迹" onClick={()=>command('undo-stroke')}><I.Undo2/></Button><I.Redo2 className="disabled"/>{brushButton}<I.Pencil/><I.Highlighter/>{eraseButton}<Button title="选择画布" onClick={()=>choose('canvas','当前画布','drawing')}><I.LassoSelect/></Button><Button title="添加文字" onClick={()=>choose('notes-text','笔记文字','text',s.texts['notes-text'])}><I.CaseSensitive/></Button><button aria-label="画笔颜色" onClick={()=>setPalette(!palette)}><i style={{background:s.color}}/></button><I.Image/><I.Circle/><I.Pipette/><I.MicOff/><I.SquareDashed/><I.Languages/><I.Sparkles/></div></>:<><div className="paint-topbar"><Button title="撤销笔迹" onClick={()=>command('undo-stroke')}><I.Undo2/></Button><I.Redo2 className="disabled"/><span/><Button title="画笔设置" onClick={()=>setPalette(!palette)}><I.SlidersHorizontal/></Button><Button title="选择画布" onClick={()=>choose('canvas','当前画布','drawing')}><I.LassoSelect/></Button><I.Spline/><I.Shapes/><I.Layers/><button aria-label="调色盘" onClick={()=>setPalette(!palette)}><i style={{background:s.color}}/></button></div><div className="paint-sidebar">{brushButton}<I.PenTool/>{eraseButton}<I.Pipette/><input aria-label="画笔大小" type="range" min="1" max="40" value={s.brush} onChange={e=>command('brush',Number(e.target.value))}/><input aria-label="画笔不透明度" type="range" min="1" max="100" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></div></>}
 <div className="canvas-area"><canvas ref={ref} aria-label="绘画画布" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);choose('canvas','当前画布','drawing');current.current={points:[pos(e)],color:s.color+Math.round(opacity*2.55).toString(16).padStart(2,'0'),size:s.brush,eraser:s.eraser};}} onPointerMove={e=>{if(current.current&&current.current.points.length<2000){current.current.points.push(pos(e));redraw();}}} onPointerUp={()=>{if(current.current){const st=current.current;current.current=null;command('stroke',st);}}} onPointerCancel={()=>{current.current=null;redraw();}}/>{isNotes&&<div className={'note-text '+(s.target?.id==='notes-text'?'selected':'')} onClick={()=>choose('notes-text','笔记文字','text',s.texts['notes-text'])}>{s.texts['notes-text']}</div>}</div>
 {isNotes&&overview&&<div className="notes-overview"><header><I.ChevronsLeft size={17}/><I.Locate size={17}/><I.ChevronsRight size={17}/><I.MapPinned size={17}/></header><button aria-label="选择笔记画布" onClick={()=>choose('canvas','当前画布','drawing')}><span>{s.texts['notes-text']}</span></button></div>}
 {palette&&<div className="paint-palette"><header>颜色<button aria-label="关闭调色盘" onClick={()=>setPalette(false)}><I.X size={18}/></button></header><input title="画笔颜色" aria-label="画笔颜色" type="color" value={s.color} onChange={e=>command('color',e.target.value)}/><div className="color-swatches">{['#ff5594','#232329','#f1c54b','#4b85ee','#68af98','#ffffff'].map(c=><button aria-label={c} key={c} style={{background:c}} onClick={()=>command('color',c)}/>)}</div><label>画笔大小　{s.brush}px</label><input aria-label="调整画笔大小" type="range" min="1" max="40" value={s.brush} onChange={e=>command('brush',Number(e.target.value))}/></div>}
 </div>;
}
export function LocalVideo({s,src='./media/reading-excerpt.mp4'}:{s:State;src?:string}){const ref=useRef<HTMLVideoElement>(null),last=useRef(0);
 useEffect(()=>{const v=ref.current;if(!v)return;if(s.playing){v.play().catch(()=>{command('play',false);toast('视频未能播放，请重新点击播放');});}else v.pause();},[s.playing]);
 useEffect(()=>{const v=ref.current;if(v?.duration&&Math.abs(v.currentTime/v.duration*100-s.progress)>2)v.currentTime=v.duration*s.progress/100;},[s.progress]);
 useEffect(()=>{const v=ref.current;if(v)v.currentTime=0;},[s.mediaIndex]);
 return <video className="local-video" ref={ref} src={src} playsInline muted preload="auto" onTimeUpdate={()=>{const v=ref.current;if(v?.duration&&Date.now()-last.current>500){last.current=Date.now();command('seek',v.currentTime/v.duration*100);}}} onEnded={()=>command('play',false)} onError={()=>{command('play',false);toast('视频加载失败，请重新打开应用');}}/>;
}
function Mario({s}:{s:State}){const frame=useRef<HTMLIFrameElement>(null);const [ready,setReady]=useState(false);useEffect(()=>{const f=(e:MessageEvent)=>{if(e.source===frame.current?.contentWindow&&e.data?.kind==='mario-ready')setReady(true);};window.addEventListener('message',f);return()=>{window.removeEventListener('message',f);};},[]);useEffect(()=>{frame.current?.contentWindow?.postMessage({kind:'mobile-control',keys:s.gameKeys,paused:s.gamePaused},'*');},[s.gameKeys,s.gamePaused,ready]);return <div className="game" data-ready={ready}><button className="game-back" aria-label="返回" onClick={navigateBack}><I.ChevronLeft/></button><iframe key={s.gameEpoch} ref={frame} src="./mario-classic/index.html" title="超级玛丽"/>{!ready&&<div className="game-loading" role="status">正在加载游戏…</div>}</div>;}

function WpsHome({s}:{s:State}){return <div className="wps-home"><aside><b>WPS Office</b><button className="active">首页</button><span>最近</span><span>本地文档</span></aside><section><h1>新建</h1><div className="wps-new">{(['sheet','word','slides'] as AppId[]).map((id,i)=><button key={id} onClick={()=>command('office-open',{kind:id,create:true})}><AppIcon id={id} size={48}/><strong>{['新建表格','新建文字','新建演示'][i]}</strong><I.Plus size={20}/></button>)}</div><h2>最近使用</h2>{s.officeFiles.map(file=><button className="wps-file" key={file.id} onClick={()=>command('office-open',{id:file.id})}><AppIcon id={file.kind} size={38}/><span>{file.name}<small>本地文档</small></span><I.ChevronRight size={20}/></button>)}</section></div>;}
