import type { WbObject, WbPage } from "../../../packages/core/workbuddy-documents";
export function WorkBuddyCanvas({ page, selected = [], pointer, onSelect, onBox }: { page: WbPage; selected?: string[]; pointer?: { x: number; y: number } | null; onSelect?: (id: string, additive: boolean) => void; onBox?: (box: { x: number; y: number; x2: number; y2: number }) => void }) {
  function point(e: React.PointerEvent) { const rect = e.currentTarget.getBoundingClientRect(); return { x: Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width)), y: Math.max(0, Math.min(1, (e.clientY - rect.top) / rect.height)) }; }
  return <div className="wb-controlled-canvas" data-page-id={page.id} onPointerDown={e => { if (!onBox || (e.target as Element).closest('[data-object-id]')) return; const p = point(e); e.currentTarget.dataset.boxStart = JSON.stringify(p); e.currentTarget.setPointerCapture(e.pointerId); }} onPointerUp={e => { const start = e.currentTarget.dataset.boxStart; delete e.currentTarget.dataset.boxStart; if (start) { const p = point(e), a = JSON.parse(start); onBox?.({ x: a.x, y: a.y, x2: p.x, y2: p.y }); } }}>
    <svg viewBox="0 0 960 540" aria-label={page.title}><rect width="960" height="540" fill="white" />{page.objects.map((o: WbObject) => <g key={o.id} data-object-id={o.id} role={onSelect ? "button" : undefined} aria-label={o.role} tabIndex={onSelect ? 0 : undefined} onClick={e => { e.stopPropagation(); onSelect?.(o.id, e.shiftKey); }} onKeyDown={e => { if (e.key === "Enter") onSelect?.(o.id, e.shiftKey); }}>
      <rect x={o.x} y={o.y} width={o.width} height={o.height} rx="9" fill={o.fill === "transparent" ? "transparent" : o.fill} stroke={selected.includes(o.id) ? "#168455" : "transparent"} strokeWidth="3" />
      <text x={o.x + 14} y={o.y + o.fontSize + 12} fontSize={o.fontSize} fill={o.color} fontFamily="sans-serif">{o.text.split("\n").map((line, i) => <tspan key={i} x={o.x + 14} dy={i ? o.fontSize * 1.45 : 0}>{line}</tspan>)}</text>
    </g>)}{pointer && <g transform={`translate(${pointer.x * 960},${pointer.y * 540})`}><circle r="13" fill="#16845533" stroke="#168455" strokeWidth="2" /><path d="M-19 0H19 M0-19V19" stroke="#168455" /></g>}</svg>
  </div>;
}
