import {test} from 'node:test';import assert from 'node:assert/strict';
import {Store} from './model';
const c=(type:string,value?:unknown)=>({id:crypto.randomUUID(),type,value});
function finishRead(s:Store){const a=s.state.chat.activation!;a.startedAt=Date.now()-1200;s.dispatch(c('chat-read-stage',{epoch:a.epoch,phase:'scan'}));s.dispatch(c('chat-read-stage',{epoch:a.epoch,phase:'ready'}));}
function chat(){const s=new Store();s.dispatch(c('open','wechat'));s.dispatch(c('chat-open','wx-boss'));s.dispatch(c('chat-focus',{conversation:'wx-boss'}));return s;}
test('draft edits synchronize without sending; final send is atomic and idempotent',()=>{const s=chat(),t=s.state.target!;const base={targetId:t.id,targetRevision:t.revision};const n=s.state.chat.messages['wx-boss'].length;assert.equal(s.dispatch({...c('chat-edit',{conversation:'wx-boss',text:'明天下午👨‍👩‍👧',revision:0,session:'p',sequence:1}),...base}).ok,true);assert.equal(s.state.chat.messages['wx-boss'].length,n);const send={...c('chat-submit',{conversation:'wx-boss',text:'明天下午两点见',revision:1}),...base};assert.equal(s.dispatch(send).ok,true);s.dispatch(send);assert.equal(s.state.chat.messages['wx-boss'].length,n+1);assert.equal(s.state.chat.messages['wx-boss'].at(-1)?.text,'明天下午两点见');assert.equal(s.state.chat.drafts['wx-boss'].text,'');});
test('reordered edits and edits to stale targets cannot overwrite a newer draft',()=>{const s=chat(),t=s.state.target!,base={targetId:t.id,targetRevision:t.revision};s.dispatch({...c('chat-edit',{conversation:'wx-boss',text:'新内容',revision:0,session:'p',sequence:2}),...base});assert.equal(s.dispatch({...c('chat-edit',{conversation:'wx-boss',text:'旧内容',revision:1,session:'p',sequence:1}),...base}).ok,false);s.dispatch(c('chat-open','wx-daily'));assert.equal(s.dispatch({...c('chat-submit',{conversation:'wx-boss',text:'不能发',revision:1}),...base}).ok,false);assert.equal(s.state.chat.drafts['wx-boss'].text,'新内容');});
test('suggested replies leave independent draft intact',()=>{const s=chat();s.state.chat.drafts['wx-boss'].text='未发送草稿';finishRead(s);const t=s.state.target!;const cmd={...c('chat-reply',{conversation:'wx-boss',text:'收到',contextEpoch:s.state.chat.context!.epoch,messageId:s.state.chat.context!.messageId}),targetId:t.id,targetRevision:t.revision};s.dispatch(cmd);s.dispatch(cmd);assert.equal(s.state.chat.drafts['wx-boss'].text,'未发送草稿');assert.equal(s.state.chat.messages['wx-boss'].filter(m=>m.id===cmd.id).length,1);});
test('switch cycle is fixed, stale timers rejected and WPS opens the editor at page one',()=>{const s=chat();const step=c('switch-step');s.dispatch(step);assert.equal(s.state.switcher?.index,3);s.dispatch(step);assert.equal(s.state.switcher?.index,3);s.dispatch(c('switch-step'));assert.equal(s.dispatch(c('switch-commit',{epoch:step.id})).ok,false);s.dispatch(c('switch-cancel'));assert.equal(s.state.app,'wechat');s.dispatch(c('open','mail'));const next=c('switch-step');s.dispatch(next);s.dispatch(c('switch-commit',{epoch:next.id}));assert.equal(s.state.app,'slides');assert.equal(s.state.presenting,false);assert.equal(s.state.slide,0);s.dispatch(c('open','word'));s.dispatch(c('back'));assert.equal(s.state.app,'wps');s.dispatch(c('back'));assert.equal(s.state.app,'desktop');});
test('WeChat back returns straight to desktop and releases held controls on cancellation',()=>{const s=chat();s.dispatch(c('back'));assert.equal(s.state.app,'desktop');s.dispatch(c('open','wechat'));assert.equal(s.state.chat.conversation,'wx-boss');s.dispatch(c('back'));assert.equal(s.state.app,'desktop');s.dispatch(c('open','mario'));s.dispatch(c('game-keys',['ArrowRight','Shift','Space']));s.dispatch(c('switch-step'));assert.deepEqual(s.state.gameKeys,[]);s.dispatch(c('release'));assert.equal(s.state.switcher,null);});
