import {test} from 'node:test';import assert from 'node:assert/strict';import {Store,initialState,totals,initialProducts,apps,mails} from './model';
let i=0;const cmd=(type:string,value?:unknown)=>({id:`t${++i}`,type,value});
function selectCell(store:Store,row=0){store.dispatch(cmd('open','sheet'));store.dispatch(cmd('select',{id:`cell:${row}:quantity`,label:'数量',kind:'number',value:'30'}));return {app:store.state.app,targetId:store.state.target!.id,targetRevision:store.state.target!.revision};}
test('fictional sales quote arithmetic is consistent',()=>{assert.deepEqual(totals(initialProducts),{cost:156900,revenue:190380,profit:33480,margin:33480/190380*100});assert.ok(mails.every(m=>m.address.endsWith('@example.com')));});
test('reject changed target and preserve values',()=>{const st=new Store(),anchor=selectCell(st);st.dispatch(cmd('select',{id:'cell:1:quantity',label:'数量',kind:'number',value:'30'}));assert.equal(st.dispatch({...cmd('input','50'),...anchor}).ok,false);assert.equal(st.state.products[0].quantity,30);});
test('duplicate command does not execute twice or create extra undo',()=>{const st=new Store(),anchor=selectCell(st),c={...cmd('input','40'),...anchor};const ack=st.dispatch(c);assert.deepEqual(st.dispatch(c),ack);assert.equal(st.state.products[0].quantity,40);st.dispatch(cmd('undo'));assert.equal(st.state.products[0].quantity,30);assert.equal(st.dispatch(cmd('undo')).ok,false);});
test('report refresh is explicit and preserves edited copy',()=>{const st=new Store(),anchor=selectCell(st);st.state.slides[0].body='手写汇报说明';st.dispatch({...cmd('input','40'),...anchor});assert.equal(st.state.reportProducts[0].quantity,30);st.dispatch(cmd('report-refresh'));assert.equal(st.state.reportProducts[0].quantity,40);assert.equal(st.state.slides[0].body,'手写汇报说明');});
test('reject invalid quantities and discounts',()=>{const st=new Store(),anchor=selectCell(st);for(const v of ['-1','1.2','NaN',''])assert.equal(st.dispatch({...cmd('input',v),...anchor}).ok,false);assert.equal(st.state.products[0].quantity,30);});
test('mail sends internal record exactly once',()=>{const st=new Store();st.dispatch(cmd('open','mail'));st.dispatch(cmd('mail-compose','reply'));const t=st.state.target!;st.dispatch({...cmd('input','报价方案已整理。'),app:'mail',targetId:t.id,targetRevision:t.revision});const c=cmd('mail-send');assert.equal(st.dispatch(c).ok,true);st.dispatch(c);assert.equal(st.state.mails.filter(m=>m.sent).length,1);});
test('slide navigation clamps and duplicate next command stays on page',()=>{const st=new Store();st.dispatch(cmd('open','slides'));const c=cmd('slide',1);st.dispatch(c);st.dispatch(c);assert.equal(st.state.slide,1);st.dispatch(cmd('slide',99));assert.equal(st.state.slide,5);});
test('held simultaneous game keys release on app switch and disconnect',()=>{const st=new Store();st.dispatch(cmd('open','mario'));st.dispatch(cmd('game-keys',['ArrowRight','Space']));assert.equal(st.state.gameKeys.length,2);st.dispatch(cmd('release'));assert.deepEqual(st.state.gameKeys,[]);st.dispatch(cmd('game-keys',['ArrowLeft']));st.dispatch(cmd('open','mail'));assert.deepEqual(st.state.gameKeys,[]);});
test('undo invalidates target snapshots',()=>{const st=new Store(),anchor=selectCell(st);st.dispatch({...cmd('input','40'),...anchor});st.dispatch(cmd('undo'));assert.equal(st.state.target,null);assert.equal(st.dispatch({...cmd('input','41'),...anchor}).ok,false);});
test('all app entries open and clear prior target',()=>{const st=new Store();for(const a of apps){assert.equal(st.dispatch(cmd('open',a[0])).ok,true);assert.equal(st.state.app,a[0]);assert.equal(st.state.target,null);}});
test('drawing validates coordinates and can undo one stroke',()=>{const st=new Store();assert.equal(st.dispatch(cmd('stroke',{points:[[NaN,0]],color:'#123456',size:5,eraser:false})).ok,false);st.dispatch(cmd('stroke',{points:[[0,0],[1,1]],color:'#123456',size:5,eraser:false}));st.dispatch(cmd('undo-stroke'));assert.equal(st.state.strokes.length,0);});

test('managed report values refresh while human paragraphs stay intact',()=>{const st=new Store();st.dispatch(cmd('open','word'));st.dispatch(cmd('select',{id:'paragraph:2',label:'配置',kind:'text',value:st.state.paragraphs[2]}));const t=st.state.target!;st.dispatch({...cmd('input','客户要求追加备用设备'),app:'word',targetId:t.id,targetRevision:t.revision});const a=selectCell(st);st.dispatch({...cmd('input','40'),...a});st.dispatch(cmd('report-refresh'));assert.equal(st.state.paragraphs[2],'客户要求追加备用设备');assert.match(st.state.slides[1].body,/40 件/);assert.equal(st.state.target,null);});
test('presentation commands from an earlier session are rejected',()=>{const st=new Store();st.dispatch(cmd('open','slides'));st.dispatch({...cmd('present',true),sessionId:0});const session=st.state.startedAt;assert.ok(session>0);assert.equal(st.dispatch({...cmd('slide',2),sessionId:0}).ok,false);assert.equal(st.state.slide,0);assert.equal(st.dispatch({...cmd('slide',2),sessionId:session}).ok,true);});
