"""Build a local-only frame review. Private recording never enters the app or delivery ZIP."""
from pathlib import Path
import subprocess,json
root=Path(__file__).resolve().parents[1]
video=Path('/tmp/mobile-input-inspection-VID_1791414349_032.mp4')
raw=subprocess.check_output(['ffprobe','-v','error','-select_streams','v:0','-show_entries','frame=best_effort_timestamp_time','-of','json',str(video)])
pts=[float(x['best_effort_timestamp_time']) for x in json.loads(raw)['frames'] if 'best_effort_timestamp_time' in x]
scenes=[('主页',608,'desktop-home'),('应用页',2,'desktop-apps'),('工作页',615,'desktop-work'),('豆包',8,'doubao'),('微信',42,'wechat'),('邮件',120,'mail'),('邮件撰写',142,'mail-compose'),('哔哩哔哩',164,'bilibili'),('抖音',222,'douyin'),('小红书',281,'red'),('WorkBuddy',320,'workbuddy'),('阅读',418,'read'),('笔记',472,'notes'),('天生会画',542,'paint'),('小艺',642,'xiaoyi')]
html='''<!doctype html><html lang="zh-CN"><meta charset="UTF-8"><title>Mobile Input · 逐帧对照</title><style>
*{box-sizing:border-box}body{margin:0;background:#17191d;color:#ddd;font:14px system-ui}header{display:flex;gap:12px;align-items:center;padding:16px 22px;border-bottom:1px solid #45474c}h1{font-size:18px;margin:0 auto 0 0}button,select,input{font:inherit;color:inherit;background:#30333a;border:1px solid #555;border-radius:5px;padding:8px}main{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:12px}section{min-width:0}h2{font-size:13px;font-weight:400;color:#aaa}video,img{width:100%;aspect-ratio:35/23;object-fit:contain;background:#080909;display:block}.tools{display:flex;gap:12px;align-items:center;padding:12px 22px}.tools input{flex:1;padding:0}footer{padding:12px 22px;color:#9c9da5;line-height:1.8}body.overlay main{display:block;position:relative}body.overlay main section:last-child{position:absolute;inset:12px;opacity:.5;pointer-events:none}body.overlay main section:last-child h2{opacity:0}#time{font-variant-numeric:tabular-nums;min-width:250px}
</style><header><h1>Mobile Input · 逐帧对照</h1><select id="scene"></select><button id="overlay">叠加对照</button></header><main><section><h2>原始录屏 · 本地私有参考</h2><video id="source" muted preload="metadata"></video></section><section><h2>当前实现 · 1400 × 920 浏览器截图</h2><img id="render" alt="当前实现截图"></section></main><div class="tools"><button id="prev">← 前一帧</button><button id="next">后一帧 →</button><span id="time"></span><input id="scrub" type="range" min="0" value="0"></div><footer>左右方向键逐帧前进／后退。使用原视频实际 PTS，支持可变帧率。右侧是对应场景的固定实现截图，不代表原录屏每一帧均已复刻或通过验收。<br>邮件正文、联系人和附件已经换为虚构销售数据；原始邮件仅存在此本地参考。当前逐像素验收未通过，差异见项目根目录 design-qa.md。</footer><script>
const pts=PTS,scenes=SCENES,video=document.querySelector('video'),render=document.querySelector('#render'),select=document.querySelector('#scene'),scrub=document.querySelector('#scrub');let index=0;
video.src=SOURCE; scrub.max=pts.length-1;
function seek(i){index=Math.max(0,Math.min(pts.length-1,i));video.currentTime=pts[index]+.0001;scrub.value=index;document.querySelector('#time').textContent=`第 ${index+1} / ${pts.length} 帧 · ${pts[index].toFixed(4)}s`;}
scenes.forEach(([label,t,file],i)=>select.add(new Option(label,i)));
function change(){const [label,t,file]=scenes[Number(select.value)];render.src='../../artifacts/visual-qa/'+file+'.jpg';seek(pts.findIndex(x=>x>=t));}
select.onchange=change;video.onloadedmetadata=change;document.querySelector('#prev').onclick=()=>seek(index-1);document.querySelector('#next').onclick=()=>seek(index+1);scrub.oninput=()=>seek(Number(scrub.value));document.querySelector('#overlay').onclick=()=>document.body.classList.toggle('overlay');document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();seek(index+(e.key==='ArrowRight'?1:-1));}});
</script></html>'''.replace('const pts=PTS,scenes=SCENES','const pts='+json.dumps(pts)+',scenes='+json.dumps(scenes,ensure_ascii=False)).replace('video.src=SOURCE','video.src='+json.dumps(video.as_uri()))
(root/'reference/private/frame-review.html').write_text(html)
(root/'reference/frame-map.json').write_text(json.dumps({'recording':video.name,'frameCount':len(pts),'variableFrameRate':True,'scenes':[{'name':n,'time':t,'comparison':f'artifacts/visual-qa/{f}.jpg'} for n,t,f in scenes],'excluded':'112s is a desktop transition; 307s is desktop. Stable main desktop is 608s, not blurred 610s.'},ensure_ascii=False,indent=2)+'\n')
print('Wrote local frame viewer:',len(pts),'timestamped frames')
